version: "3.6"

services:

  worker:
    depends_on:
      - mysql
    image: dansolo7/worker:1.0
    environment:
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - 3306:3306
    networks:
      - backend
    container_name: mysql
    command: [--default-authentication-plugin=mysql_native_password]

networks:
  backend: