---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: voteapp
  annotations:
  labels:
    run: worker
  name: worker-server

spec:
  replicas: 1
  selector:
    matchLabels:
      run: worker
  template:
    metadata:
      labels:
        run: worker
    
    spec:
      containers:
      - image: dansolo7/voting:$BUILD_NUMBER
        imagePullPolicy: Always
        name: worker
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: voteapp-secret
              key: aws_access_key
        
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: voteapp-secret
              key: aws_secret_key
        
        - name: AWS_REGION
          value: "us-east-1"
          - name: MYSQL_HOST
          value: mysql-service
        
        - name: MYSQL_USER
          value: root
        
        - name: MYSQL_DB
          value: voteapp
        
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voteapp-secret
              key: mysql_password
      
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  namespace: voteapp
  labels:
    run: worker
  name: worker-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: worker
  sessionAffinity: None
  type: NodePort
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: voteapp
    name: worker-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
  spec:
    rules:
    - host: www.worker.com
      http:
        paths:
          - path: /
            backend:
              serviceName: worker-service
              servicePort: 80
